# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalize', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-date_created']},
        ),
        migrations.AlterField(
            model_name='receipt',
            name='of_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='journalize.JournalEntry'),
        ),
    ]
