# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
