# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('account_name', models.CharField(max_length=60)),
                ('is_active', models.BinaryField(default=0)),
                ('category', models.CharField(choices=[('a', 'Asset'), ('l', 'Liability'), ('e', 'Equity')], max_length=1)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('charge', models.CharField(choices=[('d', 'Debit'), ('c', 'Credit')], max_length=1)),
                ('date', models.DateTimeField()),
                ('effected_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Account')),
            ],
        ),
    ]
