# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.IntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2018, 2, 14, 21, 42, 29, 953000, tzinfo=utc))),
                ('is_approved', models.BinaryField(null=True)),
                ('approval_memo', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 21, 42, 29, 953000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 21, 42, 29, 953000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Journal'),
        ),
    ]
