# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180214_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 19, 55, 53, 459000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 19, 55, 53, 460000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 19, 55, 53, 460000, tzinfo=utc)),
        ),
    ]
