# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180215_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.CharField(choices=[('t', 'True'), ('f', 'False'), ('n', 'Null')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 19, 59, 37, 841000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 19, 59, 37, 841000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_approved',
            field=models.CharField(choices=[('t', 'True'), ('f', 'False'), ('n', 'Null')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 19, 59, 37, 842000, tzinfo=utc)),
        ),
    ]
