# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180215_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 3, 31, 456000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 3, 31, 457000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 3, 31, 457000, tzinfo=utc)),
        ),
    ]
