# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180215_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority (0 is top)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 21, 51, 960000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='approval_memo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 21, 51, 961000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 21, 51, 961000, tzinfo=utc)),
        ),
    ]
