# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180215_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='effected_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_journal',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 0, 50, 8, 405000, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
