# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180220_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 0, 50, 15, 627000, tzinfo=utc)),
        ),
    ]
