# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180221_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='starting_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('a', 'Asset'), ('l', 'Liability'), ('e', 'Equity')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 2, 46, 15, 142000, tzinfo=utc)),
        ),
    ]
