# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180220_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 2, 56, 43, 210786, tzinfo=utc)),
        ),
    ]
