# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180220_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_type_name', models.CharField(max_length=60, unique=True)),
                ('priority', models.IntegerField(default=0, verbose_name='Priority (0 is top)')),
                ('category', models.CharField(choices=[('a', 'Asset'), ('l', 'Liability'), ('e', 'Equity')], default='a', max_length=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountType'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
