# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180221_0256'),
        ('accounts', '0015_auto_20180221_1643'),
    ]

    operations = [
    ]
