# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20180222_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
