---

- name: Project requirements shall be installed.
  pip: requirements={{ backend }}/requirements.txt virtualenv={{ backend_env }}

- name: Project schema shall be applied to database engine.
  shell: . {{ backend_env }}/bin/activate && python manage.py migrate chdir={{ backend }}

- name: Project database will contain base fixture data.
  shell: . {{ backend_env }}/bin/activate && python manage.py loaddata base_fixtures.json chdir={{ backend }}

- name: Project database will contain fixture data for testing.
  shell: . {{ backend_env }}/bin/activate && python manage.py loaddata fixtures.json chdir={{ backend }}

- name: Project static files will be collected.
  shell: . {{ backend_env }}/bin/activate && python manage.py collectstatic --noinput chdir={{ backend }}

- name: Existing project media files will be removed.
  file: "path={{ backend }}/media state=absent"
